#!/usr/bin/env python3
"""Bake the packed int8 NFRU model into a C header for the inference backend.

Produces `nfru_model_baked.h`, which the Vulkan and DX12 backends both include. Baking
the weights in keeps the DLL self-contained (no loose .bin files to ship or fail to
find at runtime) and mirrors how the NSS backend ships its model.

Everything here is integer data: this is the int8 path, no floating point weights are
involved.
"""
import argparse
import json
import os
import sys


def emit_array(fh, name, data, ctype):
    fh.write(f"static const {ctype} {name}[{len(data)}] = {{\n")
    per = 12
    for i in range(0, len(data), per):
        chunk = data[i:i + per]
        fh.write("    " + ",".join(str(int(v)) for v in chunk) + ",\n")
    fh.write("};\n\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--packed", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    import numpy as np
    man = json.load(open(os.path.join(args.packed, "nfru_packed.json"), encoding="utf-8"))

    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("/* Generated by tools/bake_c_header.py -- do not edit.\n"
                 " *\n"
                 " * NFRU v1 int8 parameters for the dp4a inference backend.\n"
                 " * All values are integers: this is the int8 execution path.\n"
                 " */\n"
                 "#ifndef NFRU_MODEL_BAKED_H\n#define NFRU_MODEL_BAKED_H\n\n"
                 "#include <stdint.h>\n\n")

        # flat weight pool + per-layer offsets
        pool = []
        w_off = []
        bc_all, mult_all, shift_all = [], [], []
        bc_off = mult_off = shift_off = 0
        for l in man["layers"]:
            w = np.fromfile(os.path.join(args.packed, f"{l['name']}.w.bin"), dtype="<u4")
            bc = np.fromfile(os.path.join(args.packed, f"{l['name']}.bc.bin"), dtype="<i4")
            M = np.fromfile(os.path.join(args.packed, f"{l['name']}.mult.bin"), dtype="<i4")
            S = np.fromfile(os.path.join(args.packed, f"{l['name']}.shift.bin"), dtype="<i4")
            w_off.append(len(pool))
            pool.extend(int(v) for v in w)
            bc_off_next = bc_off + len(bc)
            bc_all.extend(int(v) for v in bc)
            mult_all.extend(int(v) for v in M)
            shift_all.extend(int(v) for v in S)
            l["_wOff"] = w_off[-1]
            l["_bcOff"] = bc_off
            l["_mOff"] = mult_off
            l["_sOff"] = shift_off
            bc_off, mult_off, shift_off = bc_off_next, mult_off + len(M), shift_off + len(S)

        fh.write(f"#define NFRU_MODEL_LAYER_COUNT {len(man['layers'])}\n")
        fh.write(f"#define NFRU_MODEL_TOTAL_DISPATCHES {man['totals']['totalDispatches']}\n")
        fh.write(f"#define NFRU_MODEL_WEIGHT_WORDS {len(pool)}\n")
        fh.write(f"#define NFRU_MODEL_INPUT_CHANNELS 16\n")
        fh.write(f"#define NFRU_MODEL_OUTPUT_CHANNELS 4\n")
        fh.write(f"#define NFRU_MODEL_INPUT_SCALE {man['inputScale']!r}f\n")
        fh.write(f"#define NFRU_MODEL_INPUT_ZERO_POINT {man['inputZeroPoint']}\n")
        fh.write(f"#define NFRU_MODEL_OUTPUT_SCALE {man['layers'][-1]['outputScale']!r}f\n")
        fh.write(f"#define NFRU_MODEL_OUTPUT_ZERO_POINT {man['layers'][-1]['outZeroPoint']}\n\n")

        fh.write("typedef struct NfruBakedLayer {\n"
                 "    uint32_t wOff, wWords;      /* weight pool: uint32, K4 words per out channel */\n"
                 "    uint32_t bcOff, mOff, sOff; /* bias/mult/shift pool offsets */\n"
                 "    uint32_t inC4, outC4, K4;   /* channel groups and words per out channel */\n"
                 "    uint32_t kh, kw, strideH, strideW;\n"
                 "    uint32_t padT, padB, padL, padR;\n"
                 "    int32_t  inZeroPoint, outZeroPoint;\n"
                 "    uint32_t implicitRelu;\n"
                 "    uint32_t pad0;\n"
                 "} NfruBakedLayer;\n\n")

        fh.write("static const NfruBakedLayer kNfruLayers[NFRU_MODEL_LAYER_COUNT] = {\n")
        for l in man["layers"]:
            fh.write("    {{ {wOff}u,{wWords}u, {bcOff}u,{mOff}u,{sOff}u, "
                     "{inC4}u,{outC4}u,{K4}u, {kh}u,{kw}u,{sH}u,{sW}u, "
                     "{pt}u,{pb}u,{pl}u,{pr}u, {izp}, {ozp}, {relu}u, 0u }},\n".format(
                         wOff=l["_wOff"], wWords=l["wWords"], bcOff=l["_bcOff"],
                         mOff=l["_mOff"], sOff=l["_sOff"], inC4=l["inC4"], outC4=l["outC4"],
                         K4=l["K4"], kh=l["kernel"], kw=l["kernel"],
                         sH=l["stride"][0], sW=l["stride"][1],
                         pt=l["pad"][0], pb=l["pad"][1], pl=l["pad"][2], pr=l["pad"][3],
                         izp=l["inputZeroPoint"], ozp=l["outZeroPoint"],
                         relu=1 if l["implicitRelu"] else 0))
        fh.write("};\n\n")

        emit_array(fh, "kNfruWeights", pool, "uint32_t")
        emit_array(fh, "kNfruBias", bc_all, "int32_t")
        emit_array(fh, "kNfruMult", mult_all, "int32_t")
        emit_array(fh, "kNfruShift", shift_all, "int32_t")

        fh.write("#endif /* NFRU_MODEL_BAKED_H */\n")

    print(f"wrote {args.out}")
    print(f"  layers      : {len(man['layers'])}")
    print(f"  weight words: {len(pool)}  ({len(pool)*4} bytes)")
    print(f"  bias entries: {len(bc_all)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
