#!/usr/bin/env python3
"""Embed DXIL bytecode as a C header for the DX12 backend.

Produces `nfru_shaders_dxil.h` with one uint32 array per shader, mirroring
`nfru_shaders_spv.h` on the Vulkan side. The DX12 backend creates its pipelines from
these; nothing is loaded from disk at runtime.
"""
import argparse
import os
import sys


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--conv", required=True)
    ap.add_argument("--support", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    mods = [("kNfruDxilConv", args.conv), ("kNfruDxilSupport", args.support)]
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("/* Generated by tools/embed_dxil.py -- do not edit. */\n"
                 "#ifndef NFRU_SHADERS_DXIL_H\n#define NFRU_SHADERS_DXIL_H\n\n"
                 "#include <stdint.h>\n\n")
        for name, path in mods:
            raw = open(path, "rb").read()
            if len(raw) % 4:
                print(f"{path}: size {len(raw)} is not a multiple of 4", file=sys.stderr)
                return 1
            words = [raw[i] | (raw[i + 1] << 8) | (raw[i + 2] << 16) | (raw[i + 3] << 24)
                     for i in range(0, len(raw), 4)]
            fh.write(f"/* {os.path.basename(path)}: {len(raw)} bytes */\n")
            fh.write(f"static const uint32_t {name}[{len(words)}] = {{\n")
            for i in range(0, len(words), 10):
                fh.write("    " + ",".join(f"0x{w:08x}u" for w in words[i:i + 10]) + ",\n")
            fh.write("};\n\n")
            print(f"{name}: {len(words)} words from {len(raw)} bytes")
        fh.write("#endif /* NFRU_SHADERS_DXIL_H */\n")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
