#!/usr/bin/env python3
"""Embed the NSS D3D12 shader binaries into a C header.

Mirrors tools/embed_spv.py's arrangement for the Vulkan side: same namespace, same
naming scheme, same "generated, do not edit" banner. Where the SPIR-V header stores
`unsigned int` words (because vkCreateShaderModule takes a word array), this one stores
bytes, because D3D12CreateComputePipelineState takes a byte blob. Storing words and
converting at the call site would only add a copy.

Usage:
    python tools/embed_dxil.py --out generated/nss_shaders_dxil.h \
        --shaders shaders/dxil
"""
import argparse
import os
import sys

# Kernel name -> (file stem, DXIL entry point, target profile).
# Kept here so the header records what each blob was built from; a blob without its
# provenance is a blob nobody can regenerate.
KERNELS = [
    ("conv_rq",     "conv_rq",     "CSConv",     "cs_6_4"),
    ("conv_rq2x2",  "conv_rq_2x2", "CSConv",     "cs_6_4"),  # built with -D CONV_2X2=1
    ("resize2x",    "resize2x",    "CSResize2x", "cs_6_0"),
    ("concat_copy", "concat_copy", "CSConcatCopy", "cs_6_0"),
]

BANNER = """/*
 * nss_shaders_dxil.h -- generated by tools/embed_dxil.py. Do not edit by hand.
 *
 * Embedded DXIL for the NSS D3D12 backend. Counterpart of nss_spirv_embed.h, which does
 * the same for Vulkan.
 *
 * Bytes rather than words: vkCreateShaderModule takes a uint32 array, but
 * D3D12CreateComputePipelineState takes a byte blob, so storing words here would only add
 * a conversion at the call site.
 *
 * Each blob records the file and profile it was built from, so it can be reproduced:
 *
 *     conv_rq.dxil      shaders/conv_rq.hlsl      CSConv       cs_6_4
 *     conv_rq_2x2.dxil  shaders/conv_rq.hlsl      CSConv       cs_6_4  (-D CONV_2X2=1)
 *     resize2x.dxil     shaders/resize2x.hlsl     CSResize2x   cs_6_0
 *     concat_copy.dxil  shaders/concat_copy.hlsl  CSConcatCopy cs_6_0
 *
 * cs_6_4 is required for conv_rq: dot4add_i8packed is a Shader Model 6.4 intrinsic.
 */
#pragma once

namespace nss_model {
"""


def emit(out, name, path):
    with open(path, "rb") as f:
        data = f.read()
    out.write("\nstatic const unsigned char kDxil_%s[%d] = {\n" % (name, len(data)))
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        out.write("    " + " ".join("0x%02x," % b for b in chunk) + "\n")
    out.write("};\n")
    out.write("static const unsigned int kDxil_%s_size = %du;\n" % (name, len(data)))
    return len(data)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="header to write")
    ap.add_argument("--shaders", required=True, help="directory holding the .dxil files")
    args = ap.parse_args()

    out_path = args.out
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)

    missing = []
    total = 0
    with open(out_path, "w", newline="\n") as out:
        out.write(BANNER)
        for name, stem, entry, profile in KERNELS:
            path = os.path.join(args.shaders, stem + ".dxil")
            if not os.path.isfile(path):
                missing.append(path)
                continue
            out.write("\n/* %s  <-  %s  (entry %s, %s) */\n" % (name, stem + ".dxil", entry, profile))
            n = emit(out, name, path)
            total += n
            print("  %-14s %7d bytes" % (name, n))
        out.write("\n}  // namespace nss_model\n")

    if missing:
        # Fail rather than emitting a header with kernels silently absent: the backend
        # would then create a null pipeline at run time, far from the cause.
        sys.stderr.write("missing DXIL input(s):\n")
        for m in missing:
            sys.stderr.write("  %s\n" % m)
        sys.stderr.write("Build them with shaders/build_shaders.ps1 first.\n")
        return 1

    print("  %-14s %7d bytes  ->  %s" % ("total", total, out_path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
